services:
  frontend:
    build:
      context: .
    container_name: dash_app
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - hostlib_network
    ports:
      - "8050:8050"
    command: ["gunicorn", "-b", "0.0.0.0:8050", "-w", "4", "main:server"]

networks:
  hostlib_network:
    external: true